name: Docker Build and Deploy Backend on AWS
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
 
    - name: Build Docker image
      run: docker build -t maruizlosada/backend-tfg:v1 .
 
    - name: Push Docker image to Docker Hub
      run: docker push maruizlosada/backend-tfg:v1
 
    - name: SSH into AWS and update container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_BACKEND_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/ubuntu/backend
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
